name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installer les dépendances Ubuntu
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git \
        build-essential libssl-dev libffi-dev python3-dev \
        libsqlite3-dev openjdk-11-jdk unzip wget
        pip3 install cython buildozer

    - name: Installer SDK Android avec acceptation automatique des licences
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform/android-sdk --licenses
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=${HOME}/.buildozer/android/platform/android-sdk "platforms;android-31" "build-tools;33.0.2"

    - name: Compilation APK
      run: |
        buildozer -v android debug

    - name: Charger l'APK généré
      uses: actions/upload-artifact@v4
      with:
        name: gestioninterventions-apk
        path: bin/*.apk
