name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installer les dépendances
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools git \
        build-essential libssl-dev libffi-dev python3-dev \
        libsqlite3-dev openjdk-11-jdk
        pip3 install cython buildozer

    - name: Compilation APK
      run: |
        buildozer -v android debug

    - name: Charger l'APK généré
      uses: actions/upload-artifact@v4
      with:
        name: gestioninterventions-apk
        path: bin/*.apk
